model_name: 'mask2former_r50_8xb2-90k_mixedwaymoft-512x512'
model_config_path: 'avcv/configs/models/'
load_model_paths: 'avcv/model_weights/mask2former_r50_8xb2-160k_ade20k-512x512_20221204_000055-2d1f55f1.pth'
source_model: 'mask2former_r50_8xb2-90k_waymo-512x512'
work_dir: '/store/harsh/work_dirs/'
data_path: 'waymo_open_data/'
test_data_path: 'avcv/tests/'