model_name: 'mask2former_swin-t_8xb2-160k_waymo-512x512'
model_config_path: 'avcv/configs/models/'
load_model_paths: '/home/hg22723/projects/lang-cond-task-adv-augmentation/lang_cond_task_adv_augmentation/avcv/model_weights/mask2former_swin-t_8xb2-160k_ade20k-512x512_20221203_234230-7d64e5dd.pth'
work_dir: '/store/harsh/work_dirs/'
data_path: 'waymo_open_data/'
test_data_path: 'avcv/tests/'
