model_name: 'segformer_mit-b3_8xb2-160k_mixedbddft-512x512'
model_config_path: 'avcv/configs/models/'
load_model_paths: 'avcv/model_weights/segformer_mit-b3_512x512_160k_ade20k_20210726_081410-962b98d2.pth'
work_dir: '/store/harsh/work_dirs/'
data_path: 'bdd100k/'
source_model: 'segformer_mit-b3_8xb2-160k_bdd-512x512'
test_data_path: 'avcv/tests/'

