name: control-v11.8
channels:
  - pytorch
  - defaults
  - nvidia
dependencies:
  - python=3.9
  - pip=20.3
  - cudatoolkit
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - numpy
  - pip:
      - gradio==3.44.4
      - albumentations==1.3.0
      - opencv-contrib-python
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.2
      - pytorch-lightning==1.5.0
      - omegaconf==2.3.0
      - test-tube>=0.7.5
      - streamlit==1.12.1
      - webdataset==0.2.5
      - kornia==0.6
      - open_clip_torch
      - invisible-watermark>=0.1.5
      - streamlit-drawable-canvas==0.8.0
      - torchmetrics==0.6.0
      - timm==0.6.12
      - addict==2.4.0
      - yapf==0.32.0
      - prettytable==3.6.0
      - safetensors==0.3.1
      - waymo-open-dataset-tf-2-11-0==1.6.0
      - basicsr==1.4.2
      - fvcore
      - pycocotools
      - multiprocess
      - wandb
      - tokenizers>=0.12.1
      - uvicorn
      - httpx==0.24.0
      - deepspeed==0.9.5
      - peft==0.4.0
      - transformers==4.31.0
      - accelerate==0.21.0
      - bitsandbytes==0.41.0
      - scikit-learn==1.2.2
      - sentencepiece==0.1.99
      - einops==0.6.1
      - einops-exts==0.0.4
      - gradio_client==0.5.1
      - numpy==1.21.5
      - ipdb==0.13.13
      - timm
      - git+https://github.com/openai/CLIP.git
