IMAGE:
  BDD:
    DATASET_DIR: '/store/datasets/bdd100k/'
    SYNTH_TRAIN_DIR: None # Always set in the sub programs
    TRAIN_META_PATH: 'bdd100k/'
    VAL_META_PATH: 'bdd100k/'
    PALLETE: 'coco' # coco or bdd or ade20k
control_net:
  CONFIG_PATH: 'ControlNet/models/cldm_v15.yaml'
  MODEL_PATH: 'ControlNet/models/control_v11p_sd15_seg.pth'
  FT_MODEL_PATH: 'ControlNet/models/control_v11p_sd15_av2.ckpt'
  SD_CHECKPOINT: 'ControlNet/models/v1-5-pruned.ckpt'
  USE_FINETUNED: True
SEGMENT_MODEL: 
  TYPE: 'Uniformer' # TODO: figure out how the model path is supposed to be load
GRADIO: False
SAVE:
  PATH: 'lang_data_synthesis/test_results_bdd/'
SYNTHESIS_PARAMS:
  SYNTH_TRAIN_DIR: None # Always set in the sub programs
  CONTROL : 1.0
  NUMSAMPLES : 2
  GUESS : True
  DETECT_RESOLUTION : 1024
  IMAGE_RESOLUTION: 512
  DDIMSTEPS : 50
  SCALE: 9.0
  SEED: 2000
  ETA: 0.00
  INIT_NOISE: 1.0
  ANNOTATOR: 'Seg_OFADE20K'
  A_PROMPT: 'camera like photo, realistic textures, HD quality'
  N_PROMPT: 'unrealistic, very sharp, disfigured, ugly, bad, immature, cartoon, anime, 3d, painting, b&w, cropped, worst quality'
LLAVACAPTION:
    MODELPATH: 'liuhaotian/llava-v1.5-13b'
    MODELBASE: None
    NUM_IMAGES: 'ALL' # 'ALL' or int
    prompt: "Give me a description on the objects {} and their relationships with respect to each other. Describe the background in terms of the scene (urban or rural), and image quality. Don't mention the weather conditions [clear or sunny, rainy, cloudy] or time [day, twilight, night]"
    conv_mode: 'llava_v1'
    batch_size: 16
    load_8bit: False
    load_4bit: True
    num_workers: 6
    conditions_path: 'bdd100k/metadata_train_seg.csv'
    captions_path_multi: 'bdd100k/seg_captions_train_{}.csv'
    captions_path_single: 'bdd100k/seg_captions_train.csv'
    model_per_gpu: 2
ROBUSTIFICATION:       
  test_conditions : [
    ["Clear", "Cloudy", "Rainy"],
    ["Day", "Dawn/Dusk", "Night"]
  ]
  dataset_metadata_path: ""
  classify: True
  prompt_add: [
    'An image taken during {} weather conditions.',
    'An image taken during {} time.'
    ]
  batch_size: 8
  train_file_path : 'bdd100k/metadata_train_seg.csv'
  val_file_path : 'bdd100k/metadata_val_seg.csv'
SYN_DATASET_GEN:
  target_prob_soft: 0.000001
  source_prob_soft: 0.3
  num_synthetic_images: 5000
  dataset_path: '/store/harsh/data/bdd_synthetic_ft/' # waymo_syntheitc_llava if use_llava_prompt is True
  segmentation: True
  conditions_path: 'bdd100k/'
  use_llava_prompt: False
  llava_prompt_path: 'bdd100k/seg_captions_train.csv'
  fid_results_path: 'lang_data_synthesis/synthesis_results_bdd/'
  fid_test_model: 'R50' # Swin-T or R50
  use_finetuned: True 
