#@markdown #### Replace this path with your own tfrecords. A tfrecord containing tf.Example protos as downloaded from the Waymo dataset webpage.
TRAIN_DIR: '/store/datasets/waymo/training/' #@param {type:"string"}
#@markdown #### Replace this directory with your own dataset folder for evaluation.
EVAL_DIR: '/store/datasets/waymo/validation/' #@param {type: "string"}
#@markdown #### Replace this path with the real path. Each line of the file is the "\, \" of a frame with camera segmentation labels.
TEST_SET_SOURCE: '/content/waymo-open-dataset/tutorial/2d_pvps_validation_frames.txt' #@param {type: "string"} 

#@markdown #### Replace this directory with your own testing dataset folder.
TEST_DIR: '/store/datasets/waymo/testing/' #@param {type: "string"}

# Visualization Path
VIZ_DIR: '../waymo_data/visualization/' #@param {type: "string"}

NUM_CPU: 16 #@param {type: "integer"}
#which camera frames to save
SAVE_FRAMES: [0,1,2] #@param {type: "LIST"}
SAVE_DATA: False
