#@markdown #### Replace this path with your own tfrecords. A tfrecord containing tf.Example protos as downloaded from the Waymo dataset webpage.
FILE_NAME: '../waymo_data/training/' #@param {type:"string"}
#@markdown #### Replace this directory with your own dataset folder for evaluation.
EVAL_DIR: '../waymo_data/validation/' #@param {type: "string"}
#@markdown #### Replace this path with the real path. Each line of the file is the "\, \" of a frame with camera segmentation labels.
TEST_SET_SOURCE: '/content/waymo-open-dataset/tutorial/2d_pvps_validation_frames.txt' #@param {type: "string"} 

#@markdown #### Replace this directory with your own testing dataset folder.
TEST_DIR: '/../waymo_data/testing/' #@param {type: "string"}