wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.9
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1693500674.962564
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 23
      4: 3.11.4
      5: 0.15.9
      8:
      - 1
      - 5
