model_config_path: 'avcv/configs/models/mask2former_r50_8xb2-160k_ade20k-512x512.py'
load_model_paths: 'avcv/model_weights/mask2former_r50_8xb2-160k_ade20k-512x512_20221204_000055-2d1f55f1.pth'
work_dir: 'avcv/work_dirs/mask2former_r50_8xb2-90k_waymo-512x512'
max_iters: 5
val_interval: 5
logger_interval: 1
checkpoint_interval: 5